### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by davidallenlewis** [benjamminf/craft-relabel#10]
Parse error: syntax error, unexpected '[' in RelabelPlugin.php on line 192 on MediaTemple Grid hosting (I know... I know). Doesn't happen on my local with MAMP. Maybe an outdated PHP version (5.3.29)?

**Comment by benjamminf** [comment]
Yeah you're right – Relabel only works with PHP 5.4 and greater. Can you upgrade your version?

**Comment by ttempleton** [comment]
Closing this issue due to Relabel for Craft 2 being retired and Field Labels' inability to support PHP 5.3 given Craft 3's requirement of PHP 7.0+.
