### ISSUE TITLE
Relabels get lost when reporting errors

### ISSUE THREAD

**Issue by benjamminf** [benjamminf/craft-relabel#11]
(Originally reported by @SimonEast - https://github.com/benjamminf/craft-neo/issues/73)

Steps to reproduce:

1. Create/Edit a Neo field with multiple blocks
2. Relabel some fields (using great relabel plugin)
3. Do something to cause a validation error such as leave a handle blank
4. Hit save
5. ALL fields that were previously relabelled have now been reset to default (lost their custom labels)

**Comment by benjamminf** [comment]
Since Relabel is a bit of a hack, it'll take a hack to get this behaviour fixed. I'm looking into a solution now, will update soon.

**Comment by iamjamie** [comment]
@benjamminf  Don't suppose you managed to work out a solution to this? Just lost a shed load of relabels :'(

**Comment by DougThwaites** [comment]
@iamjamie @benjamminf Also just lost a-lot of labels. Did either of you find any type of solution to either repair or stop it from re-occurring?
