### ISSUE TITLE
Craft 3 Support

### ISSUE THREAD

**Issue by seandelaney** [benjamminf/craft-relabel#16]

**Comment by pixeldeluxe** [comment]
Thanks for the great job!
Please, I miss this plugin!

**Comment by mijar** [comment]
I am just trying to minify the amount of fields used when migrating to Craft 3 project and this plugin would be of an awesome help ;)

**Comment by sergeifilippov** [comment]
You can find a Craft 3 compatible version here https://github.com/Anubarak/craft-relabel

**Comment by ttempleton** [comment]
The original Relabel has now been ported to Craft 3, has been renamed **Field Labels** for its Craft 3 release, and should be available on the Plugin Store shortly.
