### ISSUE TITLE
Feature Request: Field Labels Persist on Entries Listing Page

### ISSUE THREAD

**Issue by richhayler** [benjamminf/craft-relabel#19]
#### Description
For consistency, when viewing entries on an entries listing section where a custom field has been selected to be displayed as a table column the re-labeled field name should be used rather than the actual field name.

**Comment by ttempleton** [comment]
This is going to be a `wontfix` from a Field Labels perspective, now that field relabelling is built into Craft 3.5.  I notice that Craft (at least as of 3.5.1) doesn't seem to do this, though, so I'd recommend opening an issue for this over there if one doesn't exist and you'd still like this functionality.
