### ISSUE TITLE
Updated field labels and instructions only visible to admin users

### ISSUE THREAD

**Issue by gethyn1** [benjamminf/craft-relabel#2]
Thanks for the great plugin.

It seems updated field labels and instructions are only visible for admin users. Any users who are not admin see the original field title and instructions.

Is this an intentional feature of the plugin?

**Comment by gethyn1** [comment]
I've got this working for all users by editing line 71 in RelabelPlugin.php:

`if(craft()->request->isCpRequest() && !craft()->request->isAjaxRequest() && craft()->userSession->isAdmin())`

to:

`if(craft()->request->isCpRequest() && !craft()->request->isAjaxRequest())`

Will this have repercussions anywhere else?

**Comment by benjamminf** [comment]
Hey @gethyn1 glad you like the plugin!

You've actually discovered a pretty big oversight, can't believe it hadn't been picked up for this long. If you want to open a pull request with this fix I'd be happy to merge it, otherwise I'll do it. Thanks for reporting this issue!

**Comment by gethyn1** [comment]
Sorry - was out of the office yesterday. Good fix.

**Comment by benjamminf** [comment]
No worries, just wanted to get this fixed and rolled out quick. Thanks again!
