### ISSUE TITLE
Console Error when creating new entry from HUD

### ISSUE THREAD

**Issue by rogertinch** [benjamminf/craft-relabel#21]
#### Description
I'm unable to create a new entry from the HUD when using an Entries field.

![image](https://user-images.githubusercontent.com/11000310/55160491-703ffd80-5131-11e9-92ae-3ccb9cb5ca9a.png)

This was the console error I got:

![image](https://user-images.githubusercontent.com/11000310/55160417-4d154e00-5131-11e9-944d-0d76ff3202fc.png)

#### Steps to reproduce
1. Edit an entry using an Entries field.
2. Click on the Entries field to fire the HUD view of the entries that can be added.
3. Click on the +New Entry button in the HUD, but nothing happens.

#### Other information
- Field Labels version: 1.0.3
- Craft CMS version: 3.1.20.1

**Comment by ttempleton** [comment]
Thanks for reporting, @tinchalamo.  This has now been fixed in Field Labels 1.0.4.
