### ISSUE TITLE
Installation failure when commerce not installed but in vendor

### ISSUE THREAD

**Issue by samuelbirch** [benjamminf/craft-relabel#23]
I have commerce in my vendor folder but it is not installed within craft, so when i try and install fieldlabels i get the error:

Call to a member function getProductTypes() on null

line 222: $layouts['commerceProductType'] = $this->_mapCommerceLayouts($commerce->getProductTypes()->getAllProductTypes());

in Plugin.php

**Comment by ttempleton** [comment]
Thanks for reporting, @samuelbirch.  This will be fixed in Field Labels 1.0.4 which will be released within the next day.
