### ISSUE TITLE
256-character limit for instructions column too small

### ISSUE THREAD

**Issue by KatieMFritz** [benjamminf/craft-relabel#27]
#### Description

I'm using [Entry Instructions 1.0.4](https://github.com/sjelfull/craft-entry-instructions) to share read-only instructions with editors on entry edit screens. Some of the instructions are longer than 256 characters.

When I use Field Labels to relabel this field type, and I enter more than 256 characters under Instructions, I get this error:

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'instructions' at row 1`

As a workaround for now, I can write shorter instructions or create individual fields, but it would be great to be able to use the normal Field Labels behavior to customize a single field for different contexts! 

#### Steps to reproduce
1. Create an Entry Instructions field (character limit doesn't cause a problem here).
2. Add the Entry Instructions field to a section.
3. Relabel the Entry Instructions field with more than 256 characters under Instructions.

#### Other information
- Field Labels version: 1.0.7
- Craft CMS version: Pro 3.1.25

**Comment by pvldigital** [comment]
Thanks for reporting @KatieMFritz. This issue has been resolved in Release v1.1.0.
