### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by outline4** [benjamminf/craft-relabel#3]
Hi benjamminf, 

Great Idea. Will this work for multilingual sites as well?

**Comment by benjamminf** [comment]
I've just made the names and instructions run through the translator, so you should be able to add a translation file now to translate relabelled names and instructions. See http://craftcms.stackexchange.com/questions/10914/is-it-possible-to-translate-the-name-of-a-field-in-the-cp for more information on how to do this.
