### ISSUE TITLE
Relabelled fields in widgets

### ISSUE THREAD

**Issue by billythekid** [benjamminf/craft-relabel#4]
The re-labelled fields in 'quick post' widgets on the cp dashboard page keep their original settings and aren't re-labelled. Not sure if this is a core issue as the quick-post widgets is built-in right so doubt you can hijack the fields there. Flagging it up anyway.
Cheers

**Comment by benjamminf** [comment]
Thanks for the report. Damn, widgets was something I've overlooked. I'll get on to this soon.
