### ISSUE TITLE
Show new label in field tab

### ISSUE THREAD

**Issue by missmatsuko** [benjamminf/craft-relabel#41]
#### Description

Currently, when a field is relabelled, the original field name is crossed out. This kind of makes it look like the field is disabled or deleted.
![Screenshot of field tab with a renamed field.](https://user-images.githubusercontent.com/17884198/62739206-202f4c80-b9e9-11e9-93c1-c1ae703e7f7e.png)

If there are multiple relabelled fields on a tab, it may also be hard to find a specific one.

Is it possible to show the new field label, maybe in addition to the struck out original one?

**Comment by pvldigital** [comment]
released with v1.1.7

**Comment by missmatsuko** [comment]
@pvldigital do the readme screenshots need to be updated?

**Comment by pvldigital** [comment]
Ah yes it does. Will update the screenshots for the readme and craft plugin store.
