### ISSUE TITLE
Not displaying new labels/instructions

### ISSUE THREAD

**Issue by missmatsuko** [benjamminf/craft-relabel#42]
#### Description
I could've sworn this plugin was working for me yesterday, but today the labels aren't being relabelled. I tried resetting my code and plugins, but it didn't make a difference. 

I can still set the label and instructions for the field, and it seems to save changes properly, but the old labels still show when I go to edit an entry. The field in question is Craft's built-in Plaintext field, and the entry only has Plaintext and Redactor fields.

Added list of the active plugins I have right now. I thought it might be related to `mmikkel/cp-field-inspect` because that adds a gear to the right of a label, but disabling and uninstalling it didn't help.

#### Other information
- Field Labels version: 1.1.5
- Craft CMS version: 3.2.9
- Other installed and active plugins:
```
"angellco/spoon": "^3.3",
"barrelstrength/sprout-fields": "^3.4",
"clubstudioltd/craft-inline-svg": "^0.1",
"craftcms/aws-s3": "^1.2",
"craftcms/redactor": "^2.3",
"ether/simplemap": "^3.6",
"fruitstudios/linkit": "^1.1",
"mmikkel/cp-field-inspect": "^1.0",
"nystudio107/craft-imageoptimize": "^1.5",
"nystudio107/craft-minify": "^1.2",
"nystudio107/craft-seomatic": "^3.2",
"nystudio107/craft-templatecomments": "^1.1",
"nystudio107/craft-twigpack": "^1.1",
"spicyweb/craft-fieldlabels": "^1.1",
"spicyweb/craft-neo": "^2.4",
"studioespresso/defaulttab": "^1.3",
"supercool/tablemaker": "^2.0",
"vaersaagod/dospaces": "^1.1",
"verbb/super-table": "^2.2",
```

**Comment by dreamseeker** [comment]
Hi, I occured same issue when new entry create.

Recent Craft 3.2+ has changed DOM structure.
`Create a new entry` page no more has `input[name="action"]` and `input#apply-btn.btn.submit`.

So, I tried to add following code in https://github.com/spicywebau/craft-fieldlabels/blob/master/src/resources/js/FieldLabels.js#L353:

```js
var action = $action.val();

// add 3 lines.
if (typeof action === 'undefined' && $form.find('input[name="entryId"]').length) {
  action = 'entry-revisions/save-draft';
}

if(action)
```

After that, It looks fine.
Thanks.

**Comment by missmatsuko** [comment]
You're right, the problem seems to be only when I'm creating a new entry.
After I save the entry, the relabeled ones show.

**Comment by nfq** [comment]
That's right, it shows the default labels on new entries. Saved re-labled entries work fine. Will there be a fix for this at some point?

**Comment by pvldigital** [comment]
Hi @missmatsuko, sorry for not getting back to you about this issue, we've been really busy with multiple projects + neo and haven't had a chance to look into it. 

I'll have a look into this today.
