### ISSUE TITLE
Labels are only applied on first entry type

### ISSUE THREAD

**Issue by gglnx** [benjamminf/craft-relabel#44]
#### Description

I have a section with multiple entry types. The field labels are only applied to the first entry type (lowest ID).

#### Steps to reproduce
1. Create a section with two entry types with different field layouts.
2. Override field labels in both entry types.
3. Check entries for both types.

#### Other information
- Field Labels version: 1.1.7
- Craft CMS version: 3.3.15

**Comment by pvldigital** [comment]
Hi @gglnx,

I've testing with the provided steps but I'm unable to replicate the issue. Have you noticed any errors in the console or web.log relating to field labels?

**Comment by gglnx** [comment]
It was my error. I did hide the `entryType` field used by the JS to determinante the entry type ID: https://github.com/spicywebau/craft-fieldlabels/blob/0936e064f1a4fbd33b1985cbd07603b3de11ab28/src/resources/js/Widgets.js#L166
