### ISSUE TITLE
Cannot revert multiple labels at once.

### ISSUE THREAD

**Issue by jlcharette** [benjamminf/craft-relabel#46]
#### Description
I can't revert multiple labels. I must revert one label at the time then save the entry type. The last label isn't even reversible. When I save the entry type and go back in, the relabelling is still applied. Note: The relabelled fields are on a 4th blueprint tab.

I had to remove it one by one, and the last one wouldn't revert at all so I took it out from project.yaml manually.

#### Steps to reproduce
1. Relabel multiple fields in a 3rd or 4th blueprint tab and save the entry type.
2. Revert those labels all at once and save the entry type.
3. Return to the entry type. All "relabels" are still applied.

#### Other information
- Field Labels version: 1.1.7
- Craft CMS version: 3.3.15
- Craft Commerce version (if the issue affects Commerce):
- Browser and version (if the issue affects a specific browser): Chrome latest

**Comment by pvldigital** [comment]
Hi @jlcharette,

I can't replicate the issues you're facing. Tested with both sections and fields and it's working as intended. Can you send your web.log to plugins@spicyweb.com.au after the issues arises again?

**Comment by ttempleton** [comment]
Closing this issue, due to inactivity and not being reproducible.  If the issue persists for you with the latest Craft and Field Labels releases, please let us know and we will reopen the issue.
