### ISSUE TITLE
Support site translations for relabel name and instructions

### ISSUE THREAD

**Issue by bertoost** [benjamminf/craft-relabel#49]
#### Description

I'd prefer to write everything in English. But as for my Dutch clients I always translate field labels, instructions, options in dropdowns, select lists etc. etc.
Would be great if this awesome relabel plugin also supports this by apply the same technic as Craft does.

```php
\Craft::t('site', $label);
```

#### Other information
- Field Labels version: 1.1.10
- Craft CMS version: 3.4.15

**Comment by ttempleton** [comment]
Hi @bertoost,

This is already possible, but Field Labels uses its own translation category to achieve this, rather than using `site`, so the Field Labels-related translations will work once they are stored in `translations/<language>/fieldlabels.php`.

**Comment by bertoost** [comment]
Yeah I already found it. Thanks 👍🏻
