### ISSUE TITLE
Relabel UI shows up for Craft Commerce product types, but relabelling does not save

### ISSUE THREAD

**Issue by mildlygeeky** [benjamminf/craft-relabel#5]
Subject should pretty well explain it — I can see the Relabel dialog box, and it does the strikethrough effect, but on save the Relabel is lost when using on Craft Commerce Product Type field layouts.

**Comment by benjamminf** [comment]
Yeah, Unfortunately Relabel doesn't support Craft Commerce yet. It's on my `// TODO` list :+1:

**Comment by joshuat** [comment]
Hey, I don't know if you're accepting help on this or not, but I ran into this issue as well and created a pull request for it.

**Comment by ttempleton** [comment]
The Craft 3 release of Field Labels now features full Craft Commerce 2 support.
