### ISSUE TITLE
Transition to Craft 3.5 native relabelling

### ISSUE THREAD

**Issue by ttempleton** [benjamminf/craft-relabel#54]
The overhauled Craft 3.5 field layout designer features in-built overriding of field names and instructions.  We will need to provide a transition path to Craft 3.5 field relabelling for current users of Field Labels.

**Comment by ttempleton** [comment]
Completed in Field Labels 1.3.0.

**Comment by bertoost** [comment]
Too bad.. In 3.5 you're not able to hide field labels or instructions. This was a great feature. Sometimes I have a tab with just one matrix field, then a field-label is not necessary and I always remove them with the plugin.

[edit]
Apparently this could be done by using `__blank__`. 
https://github.com/craftcms/cms/issues/6608#issuecomment-672337354

**Comment by bertoost** [comment]
Also the provided migration is not triggering the project-config resave.. so when deploying a project, the re-labeled labels are gone :-(

[edit]
I used this temporary code to re-save the entry types and re-generate new project config files

```php
$service = \Craft::$app->getSections();
$entryTypes = $service->getAllEntryTypes();

foreach ($entryTypes as $entryType) {
        $service->saveEntryType($entryType);
}
```

**Comment by ttempleton** [comment]
@bertoost Thanks for pointing out using `__blank__` to hide a label!  Unfortunately it doesn't seem to work with instructions, though, but Field Labels 1.3.1 will reset labels to `__blank__` if the label was set to be hidden with Field Labels.  It also resolves the project config issue by rebuilding it.  Anyone reading this who's already uninstalled Field Labels, manually rebuilding the project config should work as well.
