### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by FrancisMawn** [benjamminf/craft-relabel#55]
#### Description
A javascript exception is thrown on the admin dashboard page when you don't have the Quick Post widget enabled. 

The error is located at **line 22** in **src/resources/js/Widgets.js**
`var QuickPostWidget_save = Craft.QuickPostWidget.prototype.save;`

#### Steps to reproduce
1. Visit the admin dashboard
2. Make sure you don't have the Quick Post widget activated on the page
3. Open devtools console, see exception

#### Other information
- Field Labels version: 1.2.2
- Craft CMS version: 3.4.28.1
- Craft Commerce version (if the issue affects Commerce):
- Browser and version (if the issue affects a specific browser):

**Comment by ttempleton** [comment]
Thanks for reporting this @FrancisMawn, it's now been fixed in Field Labels 1.2.4.
