### ISSUE TITLE
Incompatible with PHP 5.3

### ISSUE THREAD

**Issue by certainlyakey** [benjamminf/craft-relabel#7]
My server environment has PHP 5.3 installed. The plugin gave me the `Parse error: syntax error, unexpected '[' in .../plugins/relabel/RelabelPlugin.php on line 192` error. Could it be easily made compatible? Two Craft CMS plugins recently (CategorySources and CPFieldLinks) had the same problem, and it seems all that has been required was to change array syntax (see [here](http://stackoverflow.com/questions/16751348/difference-in-accessing-arrays-in-php-5-3-and-5-4-or-some-configuration-mismatch)).

**Comment by benjamminf** [comment]
Honestly, I'm not sure. I never code for 5.3, as I tend to take advantage of things like array dereferencing and shorthand array syntax. Looking at http://php.net/manual/en/migration54.new-features.php it might only be that particular line preventing 5.3 compatibility. But I have no plans to officially support 5.3, and I encourage you to upgrade if you're able to as Craft 3 is also dropping support.

That said, if you want to make the change yourself and see if it works on 5.3, I'll be happy to merge it into the plugin.

**Comment by ttempleton** [comment]
Closing this issue due to Relabel for Craft 2 being retired and Field Labels' inability to support PHP 5.3 given Craft 3's requirement of PHP 7.0+.
