### ISSUE TITLE
Multilingual relabel not showing language tag

### ISSUE THREAD

**Issue by atillay** [benjamminf/craft-relabel#9]
Here is the case : I have a multilingual field, when it is not relabeled, the language tag is shown on the entry form. However when I relabel it the language tag is gone. I recorded my screen because it is not easy to describe.

[craft-relabel-issue.mp4](http://alexandretillay.fr/craft-relabel-issue.mp4)

**Comment by rungta** [comment]
I’m seeing this bug as well. Relabelled fields appear to be hiding their language tags, which makes it difficult to figure out which locale’s data one is editing.

**Comment by ttempleton** [comment]
This issue has been fixed in Field Labels v1.0.7.
